# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Parti Pirate du Canada
tagline:          'Législation fondée sur les preuves'
description:      'Législation fondée sur les preuves et valeurs progressives'
url:              https://partiparate.ca
baseurl:          https://partipirateca.github.io

author:
  name:           'Parti Pirate du Canada'
  url:            https://twitter.com/partipirateca

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/partipirateca/partipirateca.github.io